name: Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-flask-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Flask server
        run: |
          cd backend
          python app.py
      - name: Run Tests
        run: |
          cd backend
          python -m pytest
